-- ── People (stored in companies table) ───────────────────────────────────────
-- name=full name, ticker=@handle, sector=role, country=employer,
-- founded_year=year joined, market_cap_billion=reputation, employee_count=followers
-- is_public=verified

INSERT INTO companies (name, ticker, sector, country, founded_year, market_cap_billion, employee_count, description, website, is_public) VALUES
('Alice Chen',         'alice_chen',      'Principal Engineer',         'Anthropic',      2019, 9.42, 4820,  'Building safe AI systems. Previously Google Brain. Love Rust and formal methods.', 'github.com/alice-chen', true),
('Björn Müller',       'rustacean',       'Systems Programmer',         'Cloudflare',     2017, 8.81, 3610,  'Making the web faster one zero-copy parse at a time. Kernel hacker at heart.', 'github.com/rustacean', true),
('Priya Patel',        'mlresearcher',    'ML Research Scientist',      'DeepMind',       2020, 9.15, 5240,  'NeurIPS 2024 Best Paper. Emergent capabilities and interpretability.', 'github.com/mlresearcher', true),
('Marcus Williams',    'devopsguru',      'Platform Engineer',          'Stripe',         2018, 7.64, 2980,  'Migrated 500 services to k8s without downtime. Platform reliability is my religion.', 'github.com/devopsguru', true),
('Sofia Rossi',        'datawrangler',    'Staff Data Engineer',        'Databricks',     2021, 6.92, 1870,  'Spark committer. Lakehouse architecture evangelist. dbt is magic.', 'github.com/datawrangler', false),
('Liam O''Brien',      'gopher_dev',      'Senior Software Engineer',   'HashiCorp',      2016, 7.28, 2140,  'Go contributor since 1.14. Terraform module author. Cloud-agnostic by principle.', 'github.com/gopher-dev', true),
('Yuki Tanaka',        'securitymind',    'Security Engineer',          'Cloudflare',     2020, 6.43, 1560,  'eBPF for fun and profit. Zero trust, zero tolerance for flaky auth.', 'github.com/securitymind', false),
('Luna García',        'frontendwitch',   'Staff Frontend Engineer',    'Vercel',         2019, 8.94, 6810,  'React core contributor. Edge rendering obsessive. CSS is a programming language.', 'github.com/frontendwitch', true),
('Amir Hassan',        'quantumleap',     'Quantum Research Engineer',  'IBM Research',   2022, 5.71, 980,   'Quantum ML at IBM Research. Teaching qubits to learn.', 'github.com/quantumleap', false),
('Fatima Al-Zahrawi',  'ossenthusiast',   'ML Engineer',                'Hugging Face',   2020, 8.12, 3290,  'Open source everything. Fine-tuned 200+ models. Democratizing AI one PR at a time.', 'github.com/ossenthusiast', true),
('Raj Krishnamurthy',  'k8swhisperer',    'Staff SRE',                  'Google',         2017, 8.68, 4120,  'Kubernetes contributor. Previously built GKE autopilot. CKA certified instructor.', 'github.com/k8swhisperer', true),
('Emma Lindström',     'rustformers',     'Research Engineer',          'Mozilla',        2018, 7.89, 2760,  'WebAssembly spec contributor. Rewrote Firefox CSS engine in Rust.', 'github.com/rustformers', true),
('Chen Wei',           'dboptimizer',     'Database Engineer',          'PlanetScale',    2021, 6.18, 1340,  'MySQL internals, Vitess contributor, query plan obsessed.', 'github.com/dboptimizer', false),
('Nadia Okonkwo',      'aiethicist',      'AI Policy Researcher',       'Anthropic',      2021, 7.54, 2890,  'AI policy and ethics. Making sure the models we build don''t break society.', 'github.com/aiethicist', true),
('Tobias Schneider',   'grpcmaster',      'Software Architect',         'Temporal',       2020, 6.84, 1650,  'Distributed systems, durable execution, workflow engines. Temporal contributor.', 'github.com/grpcmaster', false),
('Hana Kimura',        'vectorvault',     'Developer Advocate',         'Weaviate',       2022, 7.01, 2430,  'Vector search, semantic embeddings, RAG pipelines. Building the semantic web.', 'github.com/vectorvault', true),
('Dario Romano',       'llmwhisperer',    'Research Engineer',          'Mistral AI',     2023, 8.35, 3870,  'Training efficient LLMs. Mixtral co-author. Open weights are non-negotiable.', 'github.com/llmwhisperer', true),
('Sarah Kim',          'cloudnative',     'Senior Engineer',            'Neon',           2022, 5.49, 870,   'Serverless Postgres, branching workflows, scale-to-zero. DB infra nerd.', 'github.com/cloudnative', false),
('Pavel Novak',        'cryptoeng',       'Security Engineer',          'HashiCorp',      2019, 5.96, 1120,  'Vault contributor. HashiCorp mTLS, PKI, secrets at scale.', 'github.com/cryptoeng', false),
('Mei Lin',            'edgerunner',      'Infrastructure Engineer',    'Fly.io',         2021, 6.75, 1980,  'Global deployment, anycast routing, multi-region Postgres.', 'github.com/edgerunner', true);

-- ── Open-source projects (products table) ────────────────────────────────────
-- company_id refs the person above, rating=community score, monthly_active_users_million=stars÷1000

INSERT INTO products (company_id, name, category, launch_year, version, description, tags, rating, monthly_active_users_million) VALUES
(1,  'safetykit',        'Rust · AI Safety',       2022, 'v0.4.2',  'Formal verification toolkit for neural network properties. Proves safety invariants on transformer layers.', ARRAY['rust','AI','safety','formal-methods'], 4.7, 2.3),
(1,  'constitutionlint', 'Python · AI',            2023, 'v1.1.0',  'Linter for Constitutional AI principles. Flags policy violations in model outputs automatically.', ARRAY['python','AI','safety','anthropic'], 4.5, 1.1),
(2,  'zerocopy-http',    'Rust · Networking',      2021, 'v2.3.1',  'SIMD-accelerated HTTP/1.1 and HTTP/2 parser. Zero allocation on the hot path. 3x faster than hyper on benchmarks.', ARRAY['rust','networking','performance','simd'], 4.9, 8.7),
(2,  'ebpf-tracer',      'Rust · Systems',         2022, 'v1.0.0',  'eBPF-based request tracer for distributed systems. No code changes needed, works with any language.', ARRAY['rust','ebpf','observability','tracing'], 4.6, 3.2),
(3,  'interp-tools',     'Python · ML',            2023, 'v0.3.0',  'Mechanistic interpretability toolkit. Activation patching, causal tracing, and attention visualization.', ARRAY['python','ML','interpretability','transformers'], 4.8, 5.4),
(4,  'k8s-migrator',     'Go · DevOps',            2021, 'v3.1.2',  'Zero-downtime Kubernetes migration toolkit. Handles stateful services, traffic shifting, and rollback.', ARRAY['go','kubernetes','devops','migration'], 4.7, 4.1),
(5,  'spark-delta-kit',  'Python · Data',          2022, 'v2.0.1',  'Production patterns for Delta Lake. Schema evolution, compaction strategies, and streaming merge helpers.', ARRAY['python','spark','delta-lake','data-engineering'], 4.6, 6.8),
(6,  'tf-graph',         'Go · IaC',               2020, 'v4.2.0',  'Terraform dependency graph visualizer and impact analyzer. Shows blast radius before you apply.', ARRAY['go','terraform','IaC','devops'], 4.5, 3.9),
(8,  'edge-components',  'TypeScript · Frontend',  2023, 'v1.5.0',  'React component library optimised for edge rendering. Ships zero JavaScript for static content.', ARRAY['typescript','react','edge','frontend'], 4.8, 12.4),
(10, 'finetune-hub',     'Python · ML',            2022, 'v2.1.0',  'Fine-tuning pipeline for open-source LLMs. QLoRA, PEFT, and dataset management in one CLI.', ARRAY['python','ML','fine-tuning','LLM','open-source'], 4.9, 18.6),
(11, 'gke-autopilot',    'Go · Kubernetes',        2021, 'v5.0.0',  'Reference implementation of multi-region GKE autopilot patterns with Prometheus and Thanos.', ARRAY['go','kubernetes','GKE','SRE','multi-region'], 4.7, 7.2),
(12, 'css-rust',         'Rust · Web',             2022, 'v3.0.0',  'Lightning-fast CSS parser and layout engine written in Rust. Powers Firefox Quantum CSS.', ARRAY['rust','CSS','web','firefox','WASM'], 4.9, 21.3),
(13, 'vitess-explain',   'Go · Databases',         2023, 'v1.2.0',  'Visual query plan explorer for Vitess and MySQL. Highlights index misses and join order issues.', ARRAY['go','mysql','vitess','databases','query-optimization'], 4.6, 2.8),
(15, 'temporal-flow',    'Go · Distributed',       2022, 'v2.0.0',  'Workflow-as-code framework built on Temporal. Typed activities, retry policies, and saga patterns.', ARRAY['go','temporal','distributed','workflow','reliability'], 4.8, 4.6),
(16, 'vec-bench',        'Python · AI',            2023, 'v0.5.0',  'Benchmark suite for vector databases. Tests recall, latency, and throughput across Weaviate, Qdrant, Pinecone.', ARRAY['python','vector-db','RAG','benchmarks','AI'], 4.5, 3.1),
(17, 'mixtral-serve',    'Python · ML',            2024, 'v1.0.0',  'Production serving infrastructure for Mixtral MoE models. Optimised batching, KV cache management.', ARRAY['python','LLM','MoE','serving','open-source'], 4.8, 9.3),
(18, 'neon-branch',      'TypeScript · Databases', 2023, 'v0.8.0',  'GitHub Action for Neon database branching. Creates a fresh Postgres branch per PR, deletes on merge.', ARRAY['typescript','postgres','serverless','CI-CD','neon'], 4.7, 5.7),
(7,  'bpf-guard',        'C · Security',           2022, 'v1.3.0',  'eBPF-based runtime security enforcer. Blocks syscalls, network connections, and file access at kernel level.', ARRAY['C','ebpf','security','linux','zero-trust'], 4.6, 2.9),
(19, 'vault-k8s-sync',   'Go · Security',          2021, 'v2.4.0',  'Automatic Vault secret sync to Kubernetes secrets. Rotation, lease renewal, and audit trail included.', ARRAY['go','vault','kubernetes','secrets','security'], 4.7, 6.3),
(20, 'flyctl-regions',   'Go · Infrastructure',    2023, 'v1.1.0',  'Advanced region management for Fly.io. Latency-based routing, regional health checks, auto-failover.', ARRAY['go','fly.io','multi-region','infrastructure','edge'], 4.5, 2.4);

-- ── Blog posts / papers (innovations table) ───────────────────────────────────
-- authors=@handle array, institution=platform, citations=upvotes

INSERT INTO innovations (title, authors, institution, year, field, abstract, citations, arxiv_id, impact_score) VALUES
('Why Constitutional AI changes everything about alignment',            ARRAY['alice_chen'],          'Anthropic Blog',   2024, 'AI Safety',          'Most alignment approaches treat safety as a constraint. Constitutional AI makes it intrinsic to training — the model learns to critique and revise its own outputs.', 1420, NULL,         91.4),
('Zero-copy HTTP parsing in Rust: a deep dive',                        ARRAY['rustacean'],           'Blog',             2024, 'Systems',            'How we shaved 40% off Cloudflare request latency with a custom SIMD HTTP parser. Includes benchmarks against hyper, actix, and nginx.', 2140, NULL,         88.7),
('Mechanistic interpretability: a practitioner''s guide',             ARRAY['mlresearcher'],        'arXiv',            2024, 'ML Research',        'How to use activation patching and causal tracing to understand what your model does. Covers superposition, circuits, and feature visualization.', 1540, '2401.11234', 93.2),
('Migrating 500 microservices to Kubernetes without downtime',         ARRAY['devopsguru'],          'Stripe Blog',      2023, 'Platform Eng',       'The 18-month journey, the near-disasters, and the monitoring setup that saved us. Full runbook included.', 1870, NULL,         87.1),
('Delta Lake in production: what the docs don''t tell you',           ARRAY['datawrangler'],        'dev.to',           2024, 'Data Engineering',   'The gotchas, the tuning knobs, and the schema evolution patterns we learned building petabyte-scale lakehouses.', 980,  NULL,         82.4),
('Terraform at scale: managing 10,000 resources without going insane', ARRAY['gopher_dev'],          'HashiCorp Blog',   2023, 'DevOps',             'Module patterns, state management strategies, and the drift detection setup that actually works in enterprise.', 1340, NULL,         84.9),
('eBPF security in production: lessons from two years at Cloudflare',  ARRAY['securitymind'],        'Blog',             2024, 'Security',           'What we learned running eBPF-based intrusion detection across 300 PoPs. Pitfalls, false positives, and kernel version hell.', 920,  NULL,         81.3),
('The future of frontend is at the edge',                              ARRAY['frontendwitch'],       'Vercel Blog',      2024, 'Frontend',           'Why server components, edge rendering, and streaming make SPAs look like 2018. React 19 changes everything.', 2240, NULL,         89.5),
('Quantum advantage for ML: myth or near future?',                     ARRAY['quantumleap'],         'arXiv',            2024, 'Quantum Computing',  'A sober look at where quantum speedups for machine learning are plausible in the 2025-2030 timeframe. No hype.', 780,  '2402.09871', 79.6),
('Fine-tuning Llama 3 on a consumer GPU: a practical guide',           ARRAY['ossenthusiast'],       'Hugging Face Blog',2024, 'ML / LLMs',          'QLoRA, PEFT, and the exact config that gets you 90% of full fine-tune quality on an RTX 4090 in under 6 hours.', 3240, NULL,         94.7),
('Multi-region Kubernetes that doesn''t bankrupt you',                 ARRAY['k8swhisperer'],        'Google Blog',      2023, 'SRE',                'Architecture patterns for global HA Kubernetes without the AWS bill shock. Covers Thanos, global load balancing, and failover.', 1120, NULL,         83.8),
('Rewriting Firefox CSS in Rust: 3 years in the trenches',            ARRAY['rustformers'],         'Mozilla Blog',     2024, 'Systems / Rust',     'What we learned shipping 2 million lines of Rust to 200 million Firefox users. Memory safety, performance, and team dynamics.', 2670, NULL,         92.1),
('Vitess query optimizer deep dive',                                   ARRAY['dboptimizer'],         'PlanetScale Blog', 2024, 'Databases',          'How Vitess plans and executes distributed MySQL queries. Join routing, scatter-gather, and when the planner makes mistakes.', 890,  NULL,         80.5),
('The risks of moving fast with AI deployment',                        ARRAY['aiethicist'],          'Anthropic Blog',   2024, 'AI Ethics',          'What responsible AI deployment looks like when the stakes are societal. Monitoring, rollback, and the cases where you should not ship.', 1120, NULL,         85.2),
('Durable execution: the programming model the cloud needs',           ARRAY['grpcmaster'],          'Temporal Blog',    2023, 'Distributed Systems','Why your distributed systems should be modeled as workflows, not state machines. How durable execution handles failures you haven''t thought of.', 1430, NULL,         86.7),
('RAG pipelines in production: the parts nobody talks about',          ARRAY['vectorvault'],         'Weaviate Blog',    2024, 'AI / RAG',           'Chunking strategies, reranking, hybrid search, and why naive RAG will disappoint you in production. Real benchmarks.', 1870, NULL,         88.3),
('Mixtral MoE: training a sparse mixture-of-experts at scale',        ARRAY['llmwhisperer'],        'arXiv',            2024, 'ML / LLMs',          'The engineering behind training Mixtral. Expert routing, load balancing, and why sparse MoE beats dense at inference time.', 2340, '2401.04088', 92.8),
('Serverless Postgres branching workflows for teams',                  ARRAY['cloudnative'],         'Neon Blog',        2024, 'Databases',          'How to use database branching in CI/CD. Every PR gets its own Postgres, schema migrations are safe, and prod stays clean.', 1240, NULL,         84.1),
('Secrets management at scale with Vault and Kubernetes',              ARRAY['cryptoeng'],           'HashiCorp Blog',   2023, 'Security / DevOps',  'How to run Vault as a secrets backbone for 50+ Kubernetes clusters. PKI, mTLS, and dynamic credentials without the chaos.', 980,  NULL,         81.9),
('Multi-region Postgres on Fly.io: a field guide',                     ARRAY['edgerunner'],          'Fly.io Blog',      2024, 'Infrastructure',     'Anycast routing, regional read replicas, and write forwarding patterns for globally distributed Postgres on Fly.io.', 860,  NULL,         80.4);

-- ── Skills / trends ────────────────────────────────────────────────────────────
INSERT INTO trends (name, category, momentum_score, year_emerged, description, related_tags, adoption_stage) VALUES
('Rust',                     'Systems',         94, 2016, 'Memory-safe systems language replacing C/C++ in production. Dominant in WASM, embedded, and performance-critical services.', ARRAY['systems','memory-safety','WASM','performance'], 'mainstream'),
('eBPF',                     'Systems',         87, 2020, 'Programmable Linux kernel observability. Powers the next generation of network security, tracing, and performance tooling.', ARRAY['linux','networking','observability','security'], 'growing'),
('Kubernetes',               'Platform',        91, 2017, 'Container orchestration standard. Every serious production workload runs on k8s or a managed variant.', ARRAY['containers','devops','SRE','cloud'], 'mainstream'),
('Large Language Models',    'AI/ML',           98, 2020, 'Foundation models trained on vast corpora enabling few-shot learning across tasks. Reshaping every software category.', ARRAY['LLM','transformers','GPT','generative-AI'], 'mainstream'),
('RAG Pipelines',            'AI/ML',           92, 2022, 'Grounding LLM outputs with retrieval from external documents. The dominant pattern for production AI that needs fresh data.', ARRAY['RAG','vector-db','LLM','semantic-search'], 'growing'),
('WebAssembly',              'Runtime',         79, 2018, 'Binary instruction format enabling near-native performance in browsers and server-side sandboxed environments.', ARRAY['WASM','performance','portable','edge'], 'growing'),
('Vector Databases',         'Databases',       88, 2021, 'Specialized stores for high-dimensional embeddings. Essential infrastructure for semantic search and RAG.', ARRAY['embeddings','semantic-search','RAG','AI'], 'growing'),
('Durable Execution',        'Architecture',    74, 2022, 'Programming model ensuring long-running workflows survive infrastructure failures through automatic checkpointing.', ARRAY['temporal','reliability','distributed','workflow'], 'emerging'),
('QLora / PEFT',             'AI/ML',           85, 2023, 'Parameter-efficient fine-tuning techniques making LLM customization accessible on consumer hardware.', ARRAY['fine-tuning','LLM','efficiency','open-source'], 'growing'),
('Serverless Postgres',      'Databases',       82, 2022, 'Postgres with auto-scaling, scale-to-zero billing, and branching. Neon and others making DB infra invisible.', ARRAY['postgres','serverless','branching','cloud'], 'growing'),
('Edge Computing',           'Infrastructure',  85, 2019, 'Running compute at the network edge close to users. Cloudflare Workers, Fly.io, and Vercel Edge Functions lead.', ARRAY['CDN','serverless','latency','Cloudflare'], 'mainstream'),
('Mechanistic Interpretability','AI/ML',        78, 2022, 'Understanding what neural networks actually compute. Circuits, superposition, and feature visualization research.', ARRAY['interpretability','AI-safety','transformers','research'], 'emerging'),
('Mixture of Experts',       'AI/ML',           83, 2023, 'Sparse model architecture routing tokens to specialized sub-networks. Mixtral proved MoE beats dense at inference cost.', ARRAY['MoE','LLM','efficiency','scaling'], 'growing'),
('Terraform / OpenTofu',     'DevOps',          88, 2014, 'Infrastructure-as-code standard. OpenTofu fork gaining momentum after HashiCorp license change.', ARRAY['IaC','DevOps','cloud','infrastructure'], 'mainstream'),
('AI Safety & Alignment',    'AI/ML',           80, 2021, 'Technical research ensuring AI systems do what humans intend. Constitutional AI, RLHF, and interpretability converge here.', ARRAY['AI-safety','alignment','RLHF','anthropic'], 'growing'),
('Multi-region Databases',   'Databases',       76, 2021, 'Globally distributed databases with strong consistency guarantees. CockroachDB, Spanner, and PlanetScale leading.', ARRAY['distributed','databases','global','consistency'], 'growing'),
('Go',                       'Languages',       86, 2012, 'Google''s systems language. Dominant for cloud-native tooling, Kubernetes ecosystem, and developer tools.', ARRAY['golang','cloud-native','kubernetes','devops'], 'mainstream'),
('Zero Trust Security',      'Security',        84, 2020, 'Never trust, always verify. mTLS everywhere, identity-based access, and continuous auth replacing perimeter security.', ARRAY['security','mTLS','identity','zero-trust'], 'growing'),
('TypeScript',               'Languages',       92, 2018, 'Typed JavaScript now the default for any serious frontend or Node.js project. React, Next.js, and Deno run on it.', ARRAY['typescript','javascript','frontend','node'], 'mainstream'),
('Observability (OpenTelemetry)','Platform',    83, 2021, 'Unified traces, metrics, and logs via OpenTelemetry. Replacing bespoke APM with vendor-neutral instrumentation.', ARRAY['observability','tracing','OpenTelemetry','SRE'], 'growing');
